### ISSUE TITLE
Chat with STT in ui

### ISSUE THREAD

**Issue by majiayu000** [paulovcmedeiros/pyRobBot#1]
Hello, this rep is a good source to learn. I want to chat with ai in streamlit, but I dont find the record button or voice button when using this app. Is there any suggestion？

**Comment by paulovcmedeiros** [comment]
Hi @majiayu000 

Thanks for reaching out. There wasn't (to the best of my knowledge) a straightforward way to do this in streamlit when I wrote this interface. I'll investigate if there are any updates that may help with this.

Feel free to give suggestions if you have any ideas :)

**Comment by majiayu000** [comment]
Thanks for reply.

I finally use [streamlit-audiorecorder](https://github.com/theevann/streamlit-audiorecorder) . It is a little long time since asked this 

question, I forget the reason why I use this, but this is which I think best.

**Comment by paulovcmedeiros** [comment]
Thanks for the tip. I have one question though: Does it capture audio client-side? This is important when deploying remotely, so I'd appreciate it if you could share any insight you may already have using this component.

I came across a discussion at <https://discuss.streamlit.io/t/speech-to-text-on-client-side-using-html5-and-streamlit-bokeh-events/7888/2> with a code suggestion but haven't been able to test it yet.

**Comment by majiayu000** [comment]
Hi, I don't quite understand your question. It capture audio on client side by js, and send the audio file to server side. At this point it is not totally client-side.

**Comment by paulovcmedeiros** [comment]
This has been fixed in the latest merge to `main`. Closing the issue. Thanks for the suggestion! :)
