### ISSUE TITLE
The streamlit web applicaton is not working

### ISSUE THREAD

**Issue by ravindranantony** [paulovcmedeiros/pyRobBot#2]
I am getting an error while opening the app

**Comment by paulovcmedeiros** [comment]
Hi @ravindranantony 

Thanks for reaching out. Can you elaborate more about the problem?

**Comment by ravindranantony** [comment]
![image](https://github.com/paulovcmedeiros/pyRobBot/assets/83961191/9f08f764-0958-47b6-8e55-2bafd2e4be8a)

**Comment by ravindranantony** [comment]
Please take a look at the screenshot

**Comment by paulovcmedeiros** [comment]
Oh, I see, you’re talking about the one hosted at the streamlit website. I’ve been working more on the chat over voice recently and hadn’t realised the streamlit-hosted app wasn’t working.

I’ll take a look as soon as my job schedule allows it. Thanks a lot for reporting this issue!

**Comment by ravindranantony** [comment]
great thank you, it will be really nice to see that and also a possibility to select a locally located model or any opensource models from huggingface
